### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by Fahad-Alsaidi** [romantico88/jitsi_videobridge_zabbix_stats#2]
Sorry to the this question. I am a new to Zabbix & jitsi. How to install the module? I have imported the xml and I add the ip. So then what?

In Jitsi meet server side, is there any thing to do?

thanks in advance.

**Comment by maxxer** [comment]
The [README](https://github.com/romantico88/jitsi_videobridge_zabbix_stats#full-documentation-of-jitsi-videobridge-colibri-stats) says you need to enable stats.

Did you install zabbix agent on the host?

**Comment by Fahad-Alsaidi** [comment]
> The [README](https://github.com/romantico88/jitsi_videobridge_zabbix_stats#full-documentation-of-jitsi-videobridge-colibri-stats) says you need to enable stats.
> 
> Did you install zabbix agent on the host?

Thanks. I figured it out.  I enabled stats then I installed zabbox agent. It works.

**Comment by maxxer** [comment]
If you think the readme is unclear you can make a pull request to enhance the docs
