### ISSUE TITLE
Macro JITSI_MEET_HOST defaults

### ISSUE THREAD

**Issue by altmas5** [romantico88/jitsi_videobridge_zabbix_stats#6]
Shouldn't `JITSI_MEET_HOST` macro have a default value of `localhost` just as `JITSI_COLIBRI_HOST`?
I'm just saying, considering that the default Severity for the trigger is `Disaster`. 
In my default Jitsi installation both services are running on localhost.

**Comment by melendur88** [comment]
That's ok :) I will change it.

**Comment by altmas5** [comment]
Cool!
